// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package trace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTrace returns the embedded CollectionSpec for trace.
func loadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace: %w", err)
	}

	return spec, err
}

// loadTraceObjects loads trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//     *traceObjects
//     *tracePrograms
//     *traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceSpecs struct {
	traceProgramSpecs
	traceMapSpecs
}

// traceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceProgramSpecs struct {
	Prog       *ebpf.ProgramSpec `ebpf:"prog"`
	ProgArp    *ebpf.ProgramSpec `ebpf:"prog_arp"`
	ProgIp     *ebpf.ProgramSpec `ebpf:"prog_ip"`
	ProgTcp    *ebpf.ProgramSpec `ebpf:"prog_tcp"`
	ProgUdp    *ebpf.ProgramSpec `ebpf:"prog_udp"`
	ProgUnkonw *ebpf.ProgramSpec `ebpf:"prog_unkonw"`
}

// traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceMapSpecs struct {
	ProgMap *ebpf.MapSpec `ebpf:"prog_map"`
}

// traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceObjects struct {
	tracePrograms
	traceMaps
}

func (o *traceObjects) Close() error {
	return _TraceClose(
		&o.tracePrograms,
		&o.traceMaps,
	)
}

// traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceMaps struct {
	ProgMap *ebpf.Map `ebpf:"prog_map"`
}

func (m *traceMaps) Close() error {
	return _TraceClose(
		m.ProgMap,
	)
}

// tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracePrograms struct {
	Prog       *ebpf.Program `ebpf:"prog"`
	ProgArp    *ebpf.Program `ebpf:"prog_arp"`
	ProgIp     *ebpf.Program `ebpf:"prog_ip"`
	ProgTcp    *ebpf.Program `ebpf:"prog_tcp"`
	ProgUdp    *ebpf.Program `ebpf:"prog_udp"`
	ProgUnkonw *ebpf.Program `ebpf:"prog_unkonw"`
}

func (p *tracePrograms) Close() error {
	return _TraceClose(
		p.Prog,
		p.ProgArp,
		p.ProgIp,
		p.ProgTcp,
		p.ProgUdp,
		p.ProgUnkonw,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed trace_bpfel.o
var _TraceBytes []byte
